name: ci

on:
  push:
    branches:
      [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to YC
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: AQAAAABXMuPqAATuwVvD3Rt1Ek3dotdiGa2iXpQ
      -
         name: Build, tag, and push image to Yandex Cloud Container Registry
         run: |
          docker build -t cr.yandex/crpmi36dos556se8cotj/lab:latest .
          docker push cr.yandex/crpmi36dos556se8cotj/lab:latest
